In [5]:
import sys
sys.path.append("..")
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
df = pd.read_csv("../data/Salary_dataset.csv")
df.head()

   Unnamed: 0  YearsExperience   Salary
0           0              1.2  39344.0
1           1              1.4  46206.0
2           2              1.6  37732.0
3           3              2.1  43526.0
4           4              2.3  39892.0

In [7]:
df.isnull()

    Unnamed: 0  YearsExperience  Salary
0        False            False   False
1        False            False   False
2        False            False   False
3        False            False   False
4        False            False   False
5        False            False   False
6        False            False   False
7        False            False   False
8        False            False   False
9        False            False   False
10       False            False   False
11       False            False   False
12       False            False   False
13       False            False   False
14       False            False   False
15       False            False   False
16       False            False   False
17       False            False   False
18       False            False   False
19       False            False   False
20       False            False   False
21       False            False   False
22       False            False   False
23       False            False   False
24       False            False   False
25       False            False   False
26       False            False   False
27       False            False   False
28       False            False   False
29       False            False   False

In [8]:
df.isnull().sum()

Unnamed: 0         0
YearsExperience    0
Salary             0
dtype: int64

In [9]:
x = df["YearsExperience"].values
y = df["Salary"].values

In [10]:
from src.linear_regression import LinearRegressionGD

model = LinearRegressionGD(lr = 0.01, n_iters = 1000)
model.fit(x,y)

print("Weight (w): ", model.w)
print("Bias (b): ", model.b)

ImportError: cannot import name 'LinearRegressionGD' from 'src.linear_regression' (d:\CODing\linear_regression\notebooks\..\src\linear_regression.py)